### ISSUE TITLE
Javadoc jar getting pulled down instead of aar

### ISSUE THREAD

**Issue by ryanhubbell** [HubbellCorp/SweetBlue#9]
As the javadoc jar is named the same as the aar, gradle prefers jars over aar files. This makes it so that if you don't specify `@aar` in the dependency, you won't have access to any sweetblue files (only the javadoc).

**Comment by Whathecode** [comment]
Thank you for documenting this! Ran into this issue and using `com.idevicesinc:sweetblue:4.0.0@aar` worked.

Any reason you don't just publish to Maven central and follow their guidelines?

**Comment by Whathecode** [comment]
It is a hassle, but a worthwhile hassle. :) Sonatype has automated the process of getting GitHub namespaces approved, so that's quick now.

I use [a Gradle plugin for publications](https://github.com/gradle-nexus/publish-plugin) which has served me quite well. Here is [an example build script for a small recent project](https://github.com/Whathecode/kotlinx.interval/blob/develop/build.gradle.kts#L127).

**Comment by ryanhubbell** [comment]
Time was/is a factor, so it's probably not going to happen. It works just fine without maven central (other than my goof up with the javadoc jar having the same name). Not like this issue wouldn't have happened if it were on maven central.

**Comment by ryanhubbell** [comment]
This has been fixed on 4.0/dev. Version 4.0.1 once released will not require you to specify `@aar`. An added bonus is that the javadoc _and_ sources jars will also be available.
